version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    env_file:
      - .env
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  web_picker:
    build:
      context: .
      dockerfile: Dockerfile.picker
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - redis
    