FROM python:3.13
WORKDIR /app

COPY poetry.lock pyproject.toml ./

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi --no-root

COPY ./bot /app/bot

RUN alembic upgrade head

CMD ["python", "-m", "bot.main"]