version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  web_picker:
    build:
      context: .
      dockerfile: Dockerfile.picker
    env_file: .env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - redis

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    command: alembic upgrade head
    depends_on:
      - redis
    volumes:
      - db-data:/data
  
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    depends_on:
      - redis
      - migrator
    volumes:
       - db-data:/data
  
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    command: celery -A bot.celery.main.app beat -l INFO
    depends_on:
      - redis
      - migrator
  
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    command: celery -A bot.celery.main.app worker -l INFO -Q reminders,maintenance --concurrency=2
    depends_on:
      - redis
      - migrator

volumes:
  db-data:
  redis-data: