FROM python:3.13
WORKDIR /app

COPY poetry.lock pyproject.toml ./

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi --no-root

COPY ./web_picker /app/web_picker

CMD ["uvicorn", "web_picker.main:app", "--host", "0.0.0.0", "--port", "8000"]
