"""Added username

Revision ID: 251440131800
Revises: 32f07aa82a55
Create Date: 2025-10-29 19:29:35.968356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251440131800'
down_revision: Union[str, Sequence[str], None] = '32f07aa82a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_note_id'), table_name='reminders')
    op.create_index(op.f('ix_reminders_note_id'), 'reminders', ['note_id'], unique=True)
    op.add_column('users', sa.Column('username', sa.String(length=128), nullable=True))
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_reminders_note_id'), table_name='reminders')
    op.create_index(op.f('ix_reminders_note_id'), 'reminders', ['note_id'], unique=False)
    # ### end Alembic commands ###
