"""Updated users constaints

Revision ID: 3d5a70321265
Revises: 2a02db738e6c
Create Date: 2025-11-04 16:56:27.173973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5a70321265'
down_revision: Union[str, Sequence[str], None] = '2a02db738e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
